# Generated by Django 5.1.4 on 2024-12-10 22:22

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='', max_length=255)),
                ('game_genre', models.CharField(default='', max_length=255)),
                ('rate_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to=application.models.game_photo_path)),
                ('game_description', models.TextField(blank=True, default='', null=True)),
                ('text_link_win', models.URLField(blank=True, default='', null=True)),
                ('text_link_ios', models.URLField(blank=True, default='', null=True)),
                ('text_link_android', models.URLField(blank=True, default='', null=True)),
                ('publish_status', models.CharField(choices=[('p', 'انتشار یافته'), ('d', 'پیش نویس')], default='D', max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی ها',
            },
        ),
    ]
