# Generated by Django 5.1.4 on 2024-12-10 22:49

import application.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['pk'], 'verbose_name': 'بازی', 'verbose_name_plural': 'بازی ها'},
        ),
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات بازی'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.CharField(default='', max_length=255, verbose_name='ژانر بازی'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=255, verbose_name='نام بازی'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=application.models.game_photo_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publish_status',
            field=models.CharField(choices=[('p', 'انتشار یافته'), ('d', 'پیش نویس')], default='D', max_length=1, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rate_score',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='game',
            name='text_link_android',
            field=models.URLField(blank=True, default='', null=True, verbose_name='لینک برای اندروید'),
        ),
        migrations.AlterField(
            model_name='game',
            name='text_link_ios',
            field=models.URLField(blank=True, default='', null=True, verbose_name='لینک برای iOS'),
        ),
        migrations.AlterField(
            model_name='game',
            name='text_link_win',
            field=models.URLField(blank=True, default='', null=True, verbose_name='لینک برای ویندوز'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('status', models.CharField(choices=[('a', 'فعال'), ('i', 'غیرفعال')], default='a', max_length=1, verbose_name='وضعیت')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.game', verbose_name='بازی')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
    ]
