# Generated by Django 5.1.4 on 2024-12-11 09:34

import blog.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='عنوان مقاله در نوار آدرس')),
                ('is_survey_on', models.BooleanField(default=False, verbose_name='نظر سنجی فعال باشد')),
                ('blog_photo', models.ImageField(blank=True, default='', null=True, upload_to=blog.models.upload_to_blog_image, verbose_name='تصویر اصلی مقاله')),
                ('short_description', models.CharField(blank=True, default='', help_text='محدودیت عبارت 500 کاراکتر می باشد', max_length=500, null=True, verbose_name='توضیح کوتاه')),
                ('text', models.TextField(default='', verbose_name='متن مقاله')),
                ('keyword', models.TextField(blank=True, default='', help_text='کلمات را وارد نموده و با علامت + آن ها را از هم دیگر جدا نمایید', null=True, verbose_name='کلمات کلیدی')),
                ('save_type', models.CharField(choices=[('N', 'پیش نویس'), ('P', 'منتشر شده')], default='N', max_length=1, verbose_name='وضعیت انتشار')),
                ('visit', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید')),
                ('comment_count', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='تعداد نظرات')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ذخیره')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_author', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده خبر')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 'blog_tbl',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='FolderLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='عنوان پوشه')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ذخیره')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='folder_author', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_children', to='blog.folderlibrary', verbose_name='پوشه والد')),
            ],
            options={
                'verbose_name': 'پوشه',
                'verbose_name_plural': 'پوشه ها',
                'db_table': 'folder_tbl',
                'ordering': ['title', 'created', 'modified', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FilesLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='عنوان فایل')),
                ('file', models.FileField(blank=True, default='', help_text='پسوند فایل های مجاز bmp MOV avi mp4 webm mkv png jpg jpeg gif ts pdf می باشد', max_length=2500, null=True, upload_to=blog.models.upload_to_file_library, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'png', 'jpg', 'jpeg', 'gif', 'ts', 'pdf', 'bmp'], message='پسوند فایل های مجاز bmp MOV avi mp4 webm mkv png jpg jpeg gif ts pdf می باشد')], verbose_name='آدرس محل ذخیره سازی')),
                ('save_type', models.CharField(choices=[('N', 'پیش نویس'), ('P', 'منتشر شده')], default='P', max_length=1, verbose_name='وضعیت انتشار')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ذخیره')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_author', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.folderlibrary', verbose_name='پوشه')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'کتاب خانه فایل ها',
                'db_table': 'files_tbl',
                'ordering': ['title', 'created', 'modified', 'pk'],
            },
        ),
    ]
