# Generated by Django 5.1.4 on 2024-12-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_survey_on',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='visit',
        ),
    ]
