# Generated by Django 5.1.4 on 2024-12-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد پریمیوم')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد پریمیوم',
                'verbose_name_plural': 'کدهای پریمیوم',
            },
        ),
    ]
